QuizMaster/Models/QuestionAnswer.cs
namespace QuizMaster.Models
{
	public class QuestionAnswer
	{
		public string? answer;
		public QuestionAnswer(string a)
		{ 
			answer = a;
		}
	}
}

QuizMaster/Models/QuestionModel.cs
using System.Text.Json;

namespace QuizMaster.Models
{
	public class QuestionModel
	{
		public string? Id { get; set; }
		public string? Question { get; set; }
		public string[]? Answers { get; set; }
		public int AnswerIndex { get; set; }
		public string? Hint { get; set; }
		public string? Explanation { get; set; }
		public string? Contributor { get; set; }
		public int[]? Ratings { get; set; }


		public override string ToString() => JsonSerializer.Serialize(this);
	}
}

QuizMaster/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace QuizMaster.Pages
{
	[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
	[IgnoreAntiforgeryToken]
	public class ErrorModel : PageModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

		private readonly ILogger<ErrorModel> _logger;

		public ErrorModel(ILogger<ErrorModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{
			RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
		}
	}
}

QuizMaster/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace QuizMaster.Pages
{
	public class IndexModel : PageModel
	{
		private readonly ILogger<IndexModel> _logger;
		public bool quiz = true;
		public bool editor = false;
		public IndexModel(ILogger<IndexModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{

		}
		public void OnPostSetQuiz()
		{
			quiz = true;
			editor = false;
			Console.WriteLine(quiz);
		}
		public void OnPostSetEditor()
		{
			quiz = false;
			editor = true;
		}
	}
}

QuizMaster/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace QuizMaster.Pages
{
	public class PrivacyModel : PageModel
	{
		private readonly ILogger<PrivacyModel> _logger;

		public PrivacyModel(ILogger<PrivacyModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{
		}
	}
}

QuizMaster/Pages/Index.cshtml
@page
@using QuizMaster.Components;
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<div class="main-container">
	<div class="header">
		<form method="post"><button type="submit" asp-page-handler="SetQuiz">Quiz</button></form>
		<form method="post"><button type="submit" asp-page-handler="SetEditor">Editor</button></form>
	</div>
	<div class="content">
		@if(Model.quiz)
			@(await Html.RenderComponentAsync<Quiz>(RenderMode.ServerPrerendered))
		else if(Model.editor)
			@(await Html.RenderComponentAsync<Editor>(RenderMode.ServerPrerendered))
	</div>
</div>

<script src="_framework/blazor.server.js"></script>

QuizMaster/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QuizMaster</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/QuizMaster.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">QuizMaster</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-action="">Quiz</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - QuizMaster - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>